resolver: nightly-2018-01-14

packages:
- .

extra-deps:
- accelerate-1.1.1.0
- accelerate-io-1.0.0.1
- accelerate-llvm-1.1.0.0
- accelerate-llvm-native-1.1.0.1
- accelerate-llvm-ptx-1.1.0.0
- git: https://github.com/TravisWhitaker/ffmpeg-light
  commit: 6e737a4fa2d570f86d837ffa198df02372ffaf81
- git: https://github.com/TravisWhitaker/cuda.git
  commit: d37b12e422a8d54dfd6e6a773fe037d63512eff1
- git: https://github.com/TravisWhitaker/nvvm.git
  commit: eb2e04f6fb38660d56f2abe43ac96ac2016cdff2

system-ghc: true
